### ISSUE TITLE
a la hora de elegir ciudad si escribes atera da error

### ISSUE THREAD

**Issue by ghost** [Midoiaga/PMOOPROIEKTUA#13]
```
2-(r)en txanda
1 hiri dituzu
Zein hiri aukeratu nahi duzu :
2 hiria(4,8) HP: 1
Atera
java.lang.NullPointerException
	at civilization.Jokalaria.hiriakAdministratu(Jokalaria.java:43)
	at civilization.Jokalaria.txanda(Jokalaria.java:21)
	at civilization.Civilization.partida(Civilization.java:83)
	at civilization.Civilization$1.run(Civilization.java:161)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ghost** [comment]
lol, es porque falta la aukera de "Atera" ya de paso voy a añadir "Ezer" tambien
