### ISSUE TITLE
error al elegir el nombre de una ciudad

### ISSUE THREAD

**Issue by ghost** [Midoiaga/PMOOPROIEKTUA#5]
log de la consola:

out: Sartu lehenengo jokalariaren izena: 
in:  jr
out: Sartu bigarren jokalariaren izena: 
in:  fj
out: Zein hiri aukeratu nahi duzu :
out: AnkhMorpork hiria(7,17)
in: AnkhMorpork
error:
java.lang.NullPointerException
	at civilization.Jokalaria.hiriakAdministratu(Jokalaria.java:38)
	at civilization.Jokalaria.txanda(Jokalaria.java:21)
	at civilization.Civilization.partida(Civilization.java:49)
	at civilization.Civilization$1.run(Civilization.java:72)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ghost** [comment]
no tendra que ver con lo del EventQeue ese que todavia no se que es no?

**Comment by ghost** [comment]
vale no parece ser el eventQueue

**Comment by ghost** [comment]
si metes un nombre que no es te dice que no existe y metas otro, osea eso funciona

**Comment by ghost** [comment]
el problema parece ser a la hora de acceder a los metodos de la ciudad, java se queja de NullPointerException asique sera eso

**Comment by ghost** [comment]
confirmamos, bilatuHiriaIzen(String aukera) devuelve null por alguna razon

**Comment by ghost** [comment]
el problema parece que está en izenHauDu(String pIzena) en la clase Hiria
hmm...

**Comment by ghost** [comment]
no entiendo porque sucede
AYUDAA! pls

**Comment by ghost** [comment]
si pongo que haga return true siempre el juego va hacia delante sin ningun problema, claro eso no esta vien xdxd
ya que devolveria siempre la primera ciudad

**Comment by ghost** [comment]
out: Zein hiri aukeratu nahi duzu :
out: AnkhMorpork hiria(7,17)
in:  AnkhMorpork
out: AnkhMorpork == AnkhMorpork  (esto lo saca izenHauDu() dentro de Hiria, son iguales wtfff)
out: hiria ez da existitzen
error:
java.lang.NullPointerException
	at civilization.Jokalaria.hiriakAdministratu(Jokalaria.java:41)
	at civilization.Jokalaria.txanda(Jokalaria.java:21)
	at civilization.Civilization.partida(Civilization.java:49)
	at civilization.Civilization.main(Civilization.java:80)

**Comment by ghost** [comment]
le he enviado mail a aitziber :p

**Comment by ghost** [comment]
txoo utzi python mecaguen la hostia
